config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :sms
  root 'sms#new'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/sm.rb
class Sm < ApplicationRecord
    
                   
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
    end
end

app/controllers/sms_controller.rb
class SmsController < ApplicationController
    def new
      
    end

    def create
        @sms = Sm.new(sms_params);
        account_sid = 'AC1540b23ac2a138653f7070abd20f5caa'
        auth_token = 'e63405f59f96f6eed2e9f864b4529a0a'
        @client = Twilio::REST::Client.new account_sid, auth_token
      
        @client.messages.create({
          from: '+13346506011',
          to: "+#{@sms.telephone}",
          body: "#{@sms.message}"
        })
    end

    private
        def sms_params
            params.require(:sms).permit(:telephone, :message)
        end
 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sms_helper.rb
module SmsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sms</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "sms" %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
 
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<div class="container contact-form">
            <div class="contact-image">
                <img src="https://image.ibb.co/kUagtU/rocket_contact.png" alt="rocket_contact"/>
            </div>
            <form method="post">
                <h3>Envoyer un message</h3>
               <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <input type="text" name="txtName" class="form-control" placeholder="Your Name *" value="" />
                          
                         </div>
                        
                        <div class="form-group">
                            <input type="text" name="txtPhone" class="form-control" placeholder="Your Phone Number *" value="" />
                        </div>
                        <div class="form-group">
                            <input type="submit" name="btnSubmit" class="btnContact" value="Send Message" />
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <textarea name="txtMsg" class="form-control" placeholder="Your Message *" style="width: 100%; height: 150px;"></textarea>
                        </div>
                    </div>
                </div>
            </form>
</div>

app/views/sms/new.html.erb
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
 
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->
<div class="container contact-form">
    <div class="contact-image">
        <img src="https://image.ibb.co/kUagtU/rocket_contact.png" alt="rocket_contact"/>
    </div>
            <%= form_with scope: :sms, url: sms_path, local: true do |form| %>
                <h3>Envoyer un message</h3>
                <div class="row">
                <div class="col-md-4"> </div>
                    <div class="col-md-6">
                       
                       <div class="form-group">
                        <%= form.text_field :telephone,  class: 'form-control', placeholder:'Your Phone Number *' %>
                        </div>
                       
                       <div class="form-group" >
                           <%= form.text_area :message, placeholder: 'Your Message *'  %>
                            
                        </div>
                        <div class="form-group">
                        <%= form.submit "Send Message",  class: 'btn btn-primary btn-block btn-lg' %>
                        </div>
                    </div>
                    
                </div>
            <% end %>
  </div>